version: '3.3'

services:
  server:
    build:
      context: ../
      dockerfile: ./Docker/Dockerfile
    volumes:
      - ../:/var/www/html
    container_name: expenses
    working_dir: /var/www/html
    image: expenses
    ports:
      - "8000:8000"
